version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"
  web:
    build: .
    #command: bash run_patient.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


